### ISSUE TITLE
Choose Framework

### ISSUE THREAD

**Issue by juangallostra** [javigallostra/RocoLib#1]
If possible, I would use a Python framework such as [Flask](https://palletsprojects.com/p/flask/), [Django](https://www.djangoproject.com/) or [Tornado](https://www.tornadoweb.org/en/stable/).

**Comment by javigallostra** [comment]
Seems as if you already have experience with Flask. We can choose that one if you want. All three of them are new to me so I don't really care.

**Comment by juangallostra** [comment]
Ok! I will scaffold an empty Flask project with which we can start building a first version.
