### ISSUE TITLE
Hold categories

### ISSUE THREAD

**Issue by javigallostra** [javigallostra/RocoLib#11]
When creating a new boulder problem / route, the user should be able to select "hold categories". Actually they must define at least one start and end/top hold.

- **Boulder hold categories**
  - Start
    - Left hand start + right hand start
    - Single hand start
    - Both hands start
  - Normal
  - Top
- **Route hold categories**
  - Start
  - Normal
  - End

**Comment by juangallostra** [comment]
Main categories (start, normal, top) are implemented. Subcategories haven't been included yet, but so far they don't seem necessary. If required, they will be included.
