### ISSUE TITLE
Extract production database credentials from docker image

### ISSUE THREAD

**Issue by Pan6ora** [javigallostra/RocoLib#115]
## Description

The docker image provided is connected to the database used in production. This meant that everyone can retrieve the database password by running a shell into the docker image. Then it can do everything such as setting itself as admin or things like that.

## Steps to reproduce

* Run a container
* execute `docker exec -it <container_id> /bin/cat creds.txt`

## Fix proposal

At least two different ideas:

1. removing `creds.txt` from the docker image and write in the readme that people should send you an email to ask for the database credentials
2. host a copy of the production database to be used for developpement (that everyone can modify through the docker image without problem, as it is only for dev)

If possible, I think the second one is better.

**Comment by juangallostra** [comment]
Closing as per #118
