### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by juangallostra** [javigallostra/RocoLib#6]
Heroku filesystem is ephemeral and read-only. This means that a persistent storage system has to be linked to heroku's instance in order to load and save routes and boulders. The recommended option seems to be [Amazon S3](https://aws.amazon.com/es/s3/).

Investigate how can we link both solutions.

**Comment by javigallostra** [comment]
Interesting.

**Comment by juangallostra** [comment]
I think I'll finally be using AWS DynamoDB as the storage system. It is a NoSQL Database that is friendly to JSON encoded data and I _think_ it has a free tier option which can suit our needs.

**Comment by juangallostra** [comment]
@javigallostra done. 👍 

Boulders are now stored and loaded from a dynamoDB table linked to my aws account. Currently, there is no option to delete or modify boulders from the webapp. The only option to delete or modify boulders is by directly accessing the DB.

It would be cool to have some filters that enable filtering boulders by wall section, creator, difficulty, etc.
