### ISSUE TITLE
Boulder/Route details

### ISSUE THREAD

**Issue by juangallostra** [javigallostra/RocoLib#8]
In or after the route/boulder creation page add a form to fill in details such as creator, suggested difficulty, etc.

**Comment by javigallostra** [comment]
Also add another description field: feet.
Possible options:
- Free
- FFH (Feet Follow Hands)

**Comment by juangallostra** [comment]
Current fields as per commit 6a5252fc0f9928f443267a85389ea9e4df580a18 (only applies to boulders):
- Boulder name (text field)
- Creator name (text field)
- Suggested difficulty (radio button: Green, Blue, Yellow, Red)
- Feet (radio button: Free feet, Feet follow hands, Campus)
